# Generated by Django 4.2.10 on 2024-08-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_group_course_group_name_group_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourseAccess',
        ),
    ]
